apiVersion: v1
kind: Pod
metadata:
  name: debug 
  namespace: expense 
spec:
  containers:
  # This is equal to docker. docker run -d --name nginx nginx
  - name: debug 
    image: ranjithkumar0799/debug:v1 